<a href="https://colab.research.google.com/github/MrCherveN/DataAnalist-7-0_HomeTasks/blob/main/Additional_hw_4_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Додаткове завдання з pandas
Вітаю! В цьому завданні будемо працювати з даними з опитування щодо зарплат ІТ спеціалістів на рексурсі DOU від грудня 2022 року. Впевнена, це буде цікаве дослідження, а заразом і практика pandas :)
Цей аналіз може бути корисним людині, яка обирає напрям роботи в ІТ і хоче зрозуміти тенденції. За якісного виконання цього аналізу, цей проєкт можна сміливо додавати у Ваше портфоліо!

1. Зчитайте дані з файлу `2022_dec_raw.csv`. Увага! Тут необхідно використати аргумент `pd.read_csv` `sep=';'`, бо розділювач в даних - крапка з комою.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Зчитаємо дані з файлу "2022_dec_raw.csv."
df = pd.read_csv('/content/drive/MyDrive/Python/Аналітик 7-0/Лекции/Модуль 3/data/2022_dec_raw.csv', sep=';')

2. Які колонки мають дані?

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13315 entries, 0 to 13314
Data columns (total 28 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Timestamp                                                                   13315 non-null  object
 1   Ви працюєте зараз в ІТ?                                                     13315 non-null  object
 2   Де ви зараз живете?                                                         13315 non-null  object
 3   В якій області ви зараз живете?                                             11538 non-null  object
 4   Зарплата у $$$ за місяць, лише ставка після сплати податків                 13288 non-null  object
 5   Ваша стать                                                                  13315 non-null  object
 6   Ваш вік                                                                     13315 non-null  object
 7   Яка у вас освіта?                                                           13315 non-null  object
 8   Чи є у вас науковий ступінь?                                                13204 non-null  object
 9   Знання англійської мови                                                     13315 non-null  object
 10  Оберіть вашу посаду                                                         13315 non-null  object
 11  Ваш тайтл                                                                   13315 non-null  object
 12  Ваша спеціалізація                                                          159 non-null    object
 13  Вкажіть вашу спеціалізацію                                                  2364 non-null   object
 14  Оберіть вашу спеціалізацію                                                  486 non-null    object
 15  Ваша посада                                                                 305 non-null    object
 16  Оберіть вашу посаду2                                                        560 non-null    object
 17  Ваша посада3                                                                821 non-null    object
 18  Ваша посада4                                                                485 non-null    object
 19  Ваша посада5                                                                288 non-null    object
 20  Ваша посада6                                                                353 non-null    object
 21  Ваша посада7                                                                116 non-null    object
 22  Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?  4874 non-null   object
 23  Основна мова програмування                                                  9060 non-null   object
 24  Вкажіть вашу основну спеціалізацію                                          9059 non-null   object
 25  В якій сфері працюєте?                                                      13315 non-null  object
 26  Тип компанії                                                                13315 non-null  object
 27  Загальний стаж роботи за спеціальністю                                      13315 non-null  object
dtypes: object(28)
memory usage: 2.8+ MB

3. Скільки рядків та колонок мають дані? Скільки пропущених значень має кожна з колонок?

In [5]:
# Дані мають наступну кылькысть рядків та колонок
df.shape

(13315, 28)

In [6]:
#Кількість пропущених значень по кожній колонці
df.isnull().sum()

Timestamp                                                                         0
Ви працюєте зараз в ІТ?                                                           0
Де ви зараз живете?                                                               0
В якій області ви зараз живете?                                                1777
Зарплата у $$$ за місяць, лише ставка після сплати податків                      27
Ваша стать                                                                        0
Ваш вік                                                                           0
Яка у вас освіта?                                                                 0
Чи є у вас науковий ступінь?                                                    111
Знання англійської мови                                                           0
Оберіть вашу посаду                                                               0
Ваш тайтл                                                                         0
Ваша спеціалізація                                                            13156
Вкажіть вашу спеціалізацію                                                    10951
Оберіть вашу спеціалізацію                                                    12829
Ваша посада                                                                   13010
Оберіть вашу посаду2                                                          12755
Ваша посада3                                                                  12494
Ваша посада4                                                                  12830
Ваша посада5                                                                  13027
Ваша посада6                                                                  12962
Ваша посада7                                                                  13199
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?     8441
Основна мова програмування                                                     4255
Вкажіть вашу основну спеціалізацію                                             4256
В якій сфері працюєте?                                                            0
Тип компанії                                                                      0
Загальний стаж роботи за спеціальністю                                            0
dtype: int64

In [7]:
#всього пропущених значень
df.isnull().sum().sum()

146080

4. Які колонки мають всі значення заповненими (не мають дожного None значення)? Виведіть програмно список цих колонок.

In [8]:
display(df.columns[df.notnull().all()].to_list())

['Timestamp',
 'Ви працюєте зараз в ІТ?',
 'Де ви зараз живете? ',
 'Ваша стать',
 'Ваш вік',
 'Яка у вас освіта?',
 'Знання англійської мови',
 'Оберіть вашу посаду',
 'Ваш тайтл',
 'В якій сфері працюєте?',
 'Тип компанії',
 'Загальний стаж роботи за спеціальністю']

5. Який тип мають колонки в наборі даних? Які з колонок типу object логічно на ваш погляд перетворити на числові колонки?

In [9]:
df.dtypes

Timestamp                                                                     object
Ви працюєте зараз в ІТ?                                                       object
Де ви зараз живете?                                                           object
В якій області ви зараз живете?                                               object
Зарплата у $$$ за місяць, лише ставка після сплати податків                   object
Ваша стать                                                                    object
Ваш вік                                                                       object
Яка у вас освіта?                                                             object
Чи є у вас науковий ступінь?                                                  object
Знання англійської мови                                                       object
Оберіть вашу посаду                                                           object
Ваш тайтл                                                                     object
Ваша спеціалізація                                                            object
Вкажіть вашу спеціалізацію                                                    object
Оберіть вашу спеціалізацію                                                    object
Ваша посада                                                                   object
Оберіть вашу посаду2                                                          object
Ваша посада3                                                                  object
Ваша посада4                                                                  object
Ваша посада5                                                                  object
Ваша посада6                                                                  object
Ваша посада7                                                                  object
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?    object
Основна мова програмування                                                    object
Вкажіть вашу основну спеціалізацію                                            object
В якій сфері працюєте?                                                        object
Тип компанії                                                                  object
Загальний стаж роботи за спеціальністю                                        object
dtype: object

In [10]:
df.head(2)

,Timestamp,Ви працюєте зараз в ІТ?,Де ви зараз живете?,В якій області ви зараз живете?,"Зарплата у $$$ за місяць, лише ставка після сплати податків",Ваша стать,Ваш вік,Яка у вас освіта?,Чи є у вас науковий ступінь?,Знання англійської мови,...,Ваша посада4,Ваша посада5,Ваша посада6,Ваша посада7,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,Вкажіть вашу основну спеціалізацію,В якій сфері працюєте?,Тип компанії,Загальний стаж роботи за спеціальністю
0,11.30.2022 10:26:37,"Так, працюю part-time",В Україні,Івано-Франківськ чи область,4000,Чоловік,29,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blockchain,Стартап,8 років
1,11.30.2022 10:26:39,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,NaN,Чоловік,36,"Вища (бакалавр, спеціаліст, магістр)",Немає,Advanced,...,NaN,NaN,NaN,NaN,NaN,Ruby,Full Stack розробка,Public services / Government,Продуктова,3 роки

Логічно перетворити в числовий тип наступні колонки:


*   Зарплата у $$$ за місяць, лише ставка після сплати податків
*   Ваш вік

6. Трансформуйте колонки 'Ваш вік', 'Зарплата у $$$ за місяць, лише ставка після сплати податків' у тип даних float. УВАГА! Перед трансформацією подивіться, які дані містять ці колонки. Аби успішно трансформувати тип даних, треба спочатку привести рядки до того виду, який буде підходити, аби потім рядок зробити типом float.

In [11]:
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].unique()

array(['4000', nan, '2500', '500', '2800', '5500', '1400', '1200', '650',
       '6000', '6600', '850', '1000', '1500', '3000', '800', '700',
       '1100', '7500', '10600', '3300', '5000', '2400', '1800', '2100',
       '4500', '2600', '3600', '3525', '1600', '3200', '570', '6500',
       '4200', '1700', '5320', '5300', '1490', '1250', '2700', '4700',
       '1300', '400', '2000', '1577', '10000', '550', '5600', '950',
       '3550', '4750', '2200', '1850', '5200', '3040', '5100', '2250',
       '6450', '3500', '1900', '4400', '2865', '5350', '3700', '2850',
       '6150', '680', '2169', '1350', '2222', '2185', '2750', '3760',
       '2300', '200', '4275', '7700', '978', '1710', '1170', '3100',
       '5700', '1863', '2900', '3135', '3400', '4300', '730', '8500',
       '2240', '7000', '3650', '5400', '4800', '3800', '6700', '2920',
       '4100', '5800', '750', '2811', '330', '970', '900', '4250',
       '16000', '1050', '8300', '600', '2550', '3183', '7600', '2350',
       '6100', '3750', '6840', '6200', '780', '5185', '6800', '3230',
       '2330', '8000', '930', '3990', '1150', '5415', '100', '6300',
       '1750', '4340', '1080', '7125', '620', '6250', '2870', '6900',
       '4560', '2985', '5450', '4600', '3250', '833', '2950', '951',
       '2070', '4150', '3900', '376', '3285', '325', '2150', '300',
       '1425', '1010', '2050', '7400', '285', '3420', '5550', '1527',
       '475', '9000', '2230', '4845', '2570', '3050', '1390', '7800',
       '3850', '920', '8200', '3895', '955', '6650', '7200', '5225',
       '1032', '4850', '7570', '3621', '1180', '2525', '342', '810',
       '4720', '660', '3950', '1136', '345', '11000', '1475', '670',
       '5250', '2430', '560', '530', '980', '4930', '4650', '1470',
       '7300', '2145', '5510', '350', '4550', '3333', '450', '1270',
       '5650', '1933', '1990', '820', '3465', '5900', '5130', '9300',
       '7100', '960', '3920', '760', '11250', '7050', '1550', '2325',
       '4350', '2650', '1615', '4450', '5142', '2180', '3469', '6175',
       '4180', '425', '610', '4888', '1430', '580', '6666', '250', '7980',
       '1140', '6030', '1650', '1883', '3618', '14000', '1340', '9800',
       '2080', '2980', '4050', '375', '2520', '2450', '5050', '6270',
       '3450', '4900', '4810', '3380', '5870', '2831', '2280', '2620',
       '5375', '470', '3205', '6400', '3325', '6125', '615', '260', '671',
       '6825', '1370', '1277', '2340', '2245', '1410', '5750', '7840',
       '7150', '2840', '625', '5055', '5204', '1116', '1335', '1040',
       '3370', '3350', '4465', '1115', '2630', '1185', '4410', '720',
       '9500', '5150', '7900', '4020', '5180', '7220', '1310', '6135',
       '3160', '4980', '420', '2260', '2375', '1950', '815', '926',
       '3287', '9200', '190', '145', '6040', '4760', '5970', '1230',
       '5035', '597', '3330', '3344', '1575', '623', '6566', '2090',
       '8100', '480', '3530', '1682', '490', '8700', '3060', '4370',
       '4141', '1860', '3255', '1125', '940', '1670', '1764', '2177',
       '3150', '5160', '4112', '13900', '7030', '1220', '860', '12500',
       '10300', '3286', '1375', '2860', '2470', '2510', '795', '2241',
       '1995', '19500', '1090', '880', '6850', '5880', '2560', '1610',
       '909', '1154', '7550', '6460', '17000', '7187', '1006', '1542,75',
       '11675', '590', '1915', '3808', '240', '6050', '7050,82', '975',
       '8400', '3560', '2410', '7350', '4322', '2413', '3140', '1420',
       '1160', '160', '2908', '1830', '3870', '4080', '1146', '14500',
       '1580', '6386', '785', '7045', '1620', '4999', '2761', '2940',
       '290', '1825', '8800', '1565', '1377', '10750', '130', '1135',
       '2890', '3841', '4236', '6370', '547', '540', '8900', '640', '410',
       '4320', '870', '4895', '510', '1520', '910', '548', '380', '5040',
       '1865', '715', '3770', '3314', '2324', '2760', '1669', '3085',
       '3172', '430', '2063', '1590', '4430', '911', '2810', '10275',
       '1480', '1585', '2744', '2315', '4715', '8075', '866', '4801',
       '3571', '2945', '1639', '12000', '1224', '4940', '1690', '1260',
       '3570', '1640', '555', '3290', '1450', '1384', '1740', '1760',
       '1870', '957', '5522', '1591', '1045', '2965', '2660', '1330',
       '2380', '3185', '4655', '630', '3133', '6350', '637', '1440',
       '725', '1111', '4230', '7238', '1093', '2635', '758,4', '2425',
       '915', '5140', '270', '1540', '1280', '875', '435', '775', '6330',
       '872', '1696', '2337', '487', '1920', '9470', '5207', '6480',
       '3940', '575', '7893', '472', '825', '1770', '790', '144', '6750',
       '1235', '845', '5660', '5640', '3430', '3321', '5054', '520',
       '914', '1886', '7063', '405', '2023', '518', '655', '577', '2530',
       '675', '11700', '13200', '1785', '4950', '855', '2068', '6365',
       '3063', '2133', '5280', '1560', '10450', '11400', '340', '1680',
       '1205', '370', '4270', '5580', '12436', '3360', '2355', '1757',
       '997,54', '2420', '275', '495', '647', '4990', '1725', '5890',
       '1880', '7450', '2667', '8125', '1541', '1380', '770', '2875',
       '935', '3404,33', '10900', '3965', '8550', '4085', '812', '4725',
       '582', '6637', '2052', '11100', '215', '8001', '565,5', '320',
       '1192', '719', '740', '2577', '3885', '735', '1284,78', '504',
       '2412', '8600', '925', '2225', '6550', '1244,5', '3375', '1623',
       '756', '150', '180', '6996', '5850', '569', '210', '6130', '2040',
       '2033', '2715', '10500', '546', '1970', '1907', '1130', '2755',
       '2432', '1327', '1089', '3491', '2160', '230', '10200', '6325',
       '1120', '3515', '2025', '390', '1633', '9100', '4225', '690',
       '1729', '885', '80', '2156', '2370', '14687', '1525', '1110',
       '4425', '1052', '2990', '1720', '13000', '9450', '4870', '942',
       '2565', '6935', '6120', '3002,69', '280', '414', '2880', '6080',
       '2453', '890', '1385', '3610', '3845', '6140', '798', '5260',
       '4030', '7250', '8445', '6950', '1584', '1660', '4880', '7166',
       '3280', '5287', '5775', '665', '1225', '415', '4360', '225', '217',
       '1255', '5432', '5776', '3896', '4210', '1223', '1030', '1624',
       '3470', '847', '3180', '1530', '1562', '50', '2190', '4072',
       '1068', '1256', '1556', '319', '830', '1063', '824', '2125', '492',
       '2770', '617', '2277', '6526', '7083', '1268', '1060', '3095',
       '840', '3908', '1513', '1671', '5667', '7320', '4740', '3480',
       '4802', '1955', '2610', '4530', '2170', '1368', '3670', '4480',
       '1251', '882', '5411', '835', '460', '1912', '5036', '4137',
       '3720', '459', '3855', '440', '6860', '5373', '3120', '2034',
       '224', '433', '934', '542', '1730', '6792', '9400', '2612', '1711',
       '1805', '4926', '2128', '1465', '9310', '1765', '523', '1122',
       '6272', '1945', '468', '5440', '2404', '2244', '2055', '327',
       '745', '5275', '3683', '628', '3833', '2729', '2616', '677',
       '1810', '988', '2220', '2480', '12100', '1782', '5340', '310',
       '9600', '995', '1275', '5836', '5860', '2665', '784', '1195',
       '3520', '243,76', '1448', '4044,69', '908', '3830', '956', '220',
       '2335', '1472', '1075', '476', '8150', '2978', '1468', '685',
       '360', '4330', '2675', '3044', '2625', '1155', '1570', '7425',
       '1360', '4456', '683', '324', '3740', '5470', '4970', '1190',
       '1666', '1641', '9285', '2206', '3215', '826', '6790', '743',
       '4224', '4830', '1820', '710', '7175', '12600', '2285', '1274',
       '1596', '3145', '545', '1320', '589', '533', '2780', '5115',
       '1663', '563', '5162', '5190', '1408', '5950', '7375', '1528',
       '1325', '491', '2111', '5454', '1175', '1326', '272', '467',
       '2060', '1717', '2975', '1156', '3790', '958', '876', '407', '271',
       '3975', '163', '2165', '1930'], dtype=object)

In [12]:
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'] = df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].astype('str')
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'] = df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].str.strip()
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'] = df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].str.replace(',','.')
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'] = df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].astype('float')
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'] = df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].fillna(0)
df['Зарплата у $$$ за місяць, лише ставка після сплати податків'].unique()

array([ 4000.  ,     0.  ,  2500.  ,   500.  ,  2800.  ,  5500.  ,
        1400.  ,  1200.  ,   650.  ,  6000.  ,  6600.  ,   850.  ,
        1000.  ,  1500.  ,  3000.  ,   800.  ,   700.  ,  1100.  ,
        7500.  , 10600.  ,  3300.  ,  5000.  ,  2400.  ,  1800.  ,
        2100.  ,  4500.  ,  2600.  ,  3600.  ,  3525.  ,  1600.  ,
        3200.  ,   570.  ,  6500.  ,  4200.  ,  1700.  ,  5320.  ,
        5300.  ,  1490.  ,  1250.  ,  2700.  ,  4700.  ,  1300.  ,
         400.  ,  2000.  ,  1577.  , 10000.  ,   550.  ,  5600.  ,
         950.  ,  3550.  ,  4750.  ,  2200.  ,  1850.  ,  5200.  ,
        3040.  ,  5100.  ,  2250.  ,  6450.  ,  3500.  ,  1900.  ,
        4400.  ,  2865.  ,  5350.  ,  3700.  ,  2850.  ,  6150.  ,
         680.  ,  2169.  ,  1350.  ,  2222.  ,  2185.  ,  2750.  ,
        3760.  ,  2300.  ,   200.  ,  4275.  ,  7700.  ,   978.  ,
        1710.  ,  1170.  ,  3100.  ,  5700.  ,  1863.  ,  2900.  ,
        3135.  ,  3400.  ,  4300.  ,   730.  ,  8500.  ,  2240.  ,
        7000.  ,  3650.  ,  5400.  ,  4800.  ,  3800.  ,  6700.  ,
        2920.  ,  4100.  ,  5800.  ,   750.  ,  2811.  ,   330.  ,
         970.  ,   900.  ,  4250.  , 16000.  ,  1050.  ,  8300.  ,
         600.  ,  2550.  ,  3183.  ,  7600.  ,  2350.  ,  6100.  ,
        3750.  ,  6840.  ,  6200.  ,   780.  ,  5185.  ,  6800.  ,
        3230.  ,  2330.  ,  8000.  ,   930.  ,  3990.  ,  1150.  ,
        5415.  ,   100.  ,  6300.  ,  1750.  ,  4340.  ,  1080.  ,
        7125.  ,   620.  ,  6250.  ,  2870.  ,  6900.  ,  4560.  ,
        2985.  ,  5450.  ,  4600.  ,  3250.  ,   833.  ,  2950.  ,
         951.  ,  2070.  ,  4150.  ,  3900.  ,   376.  ,  3285.  ,
         325.  ,  2150.  ,   300.  ,  1425.  ,  1010.  ,  2050.  ,
        7400.  ,   285.  ,  3420.  ,  5550.  ,  1527.  ,   475.  ,
        9000.  ,  2230.  ,  4845.  ,  2570.  ,  3050.  ,  1390.  ,
        7800.  ,  3850.  ,   920.  ,  8200.  ,  3895.  ,   955.  ,
        6650.  ,  7200.  ,  5225.  ,  1032.  ,  4850.  ,  7570.  ,
        3621.  ,  1180.  ,  2525.  ,   342.  ,   810.  ,  4720.  ,
         660.  ,  3950.  ,  1136.  ,   345.  , 11000.  ,  1475.  ,
         670.  ,  5250.  ,  2430.  ,   560.  ,   530.  ,   980.  ,
        4930.  ,  4650.  ,  1470.  ,  7300.  ,  2145.  ,  5510.  ,
         350.  ,  4550.  ,  3333.  ,   450.  ,  1270.  ,  5650.  ,
        1933.  ,  1990.  ,   820.  ,  3465.  ,  5900.  ,  5130.  ,
        9300.  ,  7100.  ,   960.  ,  3920.  ,   760.  , 11250.  ,
        7050.  ,  1550.  ,  2325.  ,  4350.  ,  2650.  ,  1615.  ,
        4450.  ,  5142.  ,  2180.  ,  3469.  ,  6175.  ,  4180.  ,
         425.  ,   610.  ,  4888.  ,  1430.  ,   580.  ,  6666.  ,
         250.  ,  7980.  ,  1140.  ,  6030.  ,  1650.  ,  1883.  ,
        3618.  , 14000.  ,  1340.  ,  9800.  ,  2080.  ,  2980.  ,
        4050.  ,   375.  ,  2520.  ,  2450.  ,  5050.  ,  6270.  ,
        3450.  ,  4900.  ,  4810.  ,  3380.  ,  5870.  ,  2831.  ,
        2280.  ,  2620.  ,  5375.  ,   470.  ,  3205.  ,  6400.  ,
        3325.  ,  6125.  ,   615.  ,   260.  ,   671.  ,  6825.  ,
        1370.  ,  1277.  ,  2340.  ,  2245.  ,  1410.  ,  5750.  ,
        7840.  ,  7150.  ,  2840.  ,   625.  ,  5055.  ,  5204.  ,
        1116.  ,  1335.  ,  1040.  ,  3370.  ,  3350.  ,  4465.  ,
        1115.  ,  2630.  ,  1185.  ,  4410.  ,   720.  ,  9500.  ,
        5150.  ,  7900.  ,  4020.  ,  5180.  ,  7220.  ,  1310.  ,
        6135.  ,  3160.  ,  4980.  ,   420.  ,  2260.  ,  2375.  ,
        1950.  ,   815.  ,   926.  ,  3287.  ,  9200.  ,   190.  ,
         145.  ,  6040.  ,  4760.  ,  5970.  ,  1230.  ,  5035.  ,
         597.  ,  3330.  ,  3344.  ,  1575.  ,   623.  ,  6566.  ,
        2090.  ,  8100.  ,   480.  ,  3530.  ,  1682.  ,   490.  ,
        8700.  ,  3060.  ,  4370.  ,  4141.  ,  1860.  ,  3255.  ,
        1125.  ,   940.  ,  1670.  ,  1764.  ,  2177.  ,  3150.  ,
        5160.  ,  4112.  , 13900.  ,  7030.  ,  1220.  ,   860.  ,
       12500.  , 10300.  ,  3286.  ,  1375.  ,  2860.  ,  2470.  ,
        2510.  ,   795.  ,  2241.  ,  1995.  , 19500.  ,  1090.  ,
         880.  ,  6850.  ,  5880.  ,  2560.  ,  1610.  ,   909.  ,
        1154.  ,  7550.  ,  6460.  , 17000.  ,  7187.  ,  1006.  ,
        1542.75, 11675.  ,   590.  ,  1915.  ,  3808.  ,   240.  ,
        6050.  ,  7050.82,   975.  ,  8400.  ,  3560.  ,  2410.  ,
        7350.  ,  4322.  ,  2413.  ,  3140.  ,  1420.  ,  1160.  ,
         160.  ,  2908.  ,  1830.  ,  3870.  ,  4080.  ,  1146.  ,
       14500.  ,  1580.  ,  6386.  ,   785.  ,  7045.  ,  1620.  ,
        4999.  ,  2761.  ,  2940.  ,   290.  ,  1825.  ,  8800.  ,
        1565.  ,  1377.  , 10750.  ,   130.  ,  1135.  ,  2890.  ,
        3841.  ,  4236.  ,  6370.  ,   547.  ,   540.  ,  8900.  ,
         640.  ,   410.  ,  4320.  ,   870.  ,  4895.  ,   510.  ,
        1520.  ,   910.  ,   548.  ,   380.  ,  5040.  ,  1865.  ,
         715.  ,  3770.  ,  3314.  ,  2324.  ,  2760.  ,  1669.  ,
        3085.  ,  3172.  ,   430.  ,  2063.  ,  1590.  ,  4430.  ,
         911.  ,  2810.  , 10275.  ,  1480.  ,  1585.  ,  2744.  ,
        2315.  ,  4715.  ,  8075.  ,   866.  ,  4801.  ,  3571.  ,
        2945.  ,  1639.  , 12000.  ,  1224.  ,  4940.  ,  1690.  ,
        1260.  ,  3570.  ,  1640.  ,   555.  ,  3290.  ,  1450.  ,
        1384.  ,  1740.  ,  1760.  ,  1870.  ,   957.  ,  5522.  ,
        1591.  ,  1045.  ,  2965.  ,  2660.  ,  1330.  ,  2380.  ,
        3185.  ,  4655.  ,   630.  ,  3133.  ,  6350.  ,   637.  ,
        1440.  ,   725.  ,  1111.  ,  4230.  ,  7238.  ,  1093.  ,
        2635.  ,   758.4 ,  2425.  ,   915.  ,  5140.  ,   270.  ,
        1540.  ,  1280.  ,   875.  ,   435.  ,   775.  ,  6330.  ,
         872.  ,  1696.  ,  2337.  ,   487.  ,  1920.  ,  9470.  ,
        5207.  ,  6480.  ,  3940.  ,   575.  ,  7893.  ,   472.  ,
         825.  ,  1770.  ,   790.  ,   144.  ,  6750.  ,  1235.  ,
         845.  ,  5660.  ,  5640.  ,  3430.  ,  3321.  ,  5054.  ,
         520.  ,   914.  ,  1886.  ,  7063.  ,   405.  ,  2023.  ,
         518.  ,   655.  ,   577.  ,  2530.  ,   675.  , 11700.  ,
       13200.  ,  1785.  ,  4950.  ,   855.  ,  2068.  ,  6365.  ,
        3063.  ,  2133.  ,  5280.  ,  1560.  , 10450.  , 11400.  ,
         340.  ,  1680.  ,  1205.  ,   370.  ,  4270.  ,  5580.  ,
       12436.  ,  3360.  ,  2355.  ,  1757.  ,   997.54,  2420.  ,
         275.  ,   495.  ,   647.  ,  4990.  ,  1725.  ,  5890.  ,
        1880.  ,  7450.  ,  2667.  ,  8125.  ,  1541.  ,  1380.  ,
         770.  ,  2875.  ,   935.  ,  3404.33, 10900.  ,  3965.  ,
        8550.  ,  4085.  ,   812.  ,  4725.  ,   582.  ,  6637.  ,
        2052.  , 11100.  ,   215.  ,  8001.  ,   565.5 ,   320.  ,
        1192.  ,   719.  ,   740.  ,  2577.  ,  3885.  ,   735.  ,
        1284.78,   504.  ,  2412.  ,  8600.  ,   925.  ,  2225.  ,
        6550.  ,  1244.5 ,  3375.  ,  1623.  ,   756.  ,   150.  ,
         180.  ,  6996.  ,  5850.  ,   569.  ,   210.  ,  6130.  ,
        2040.  ,  2033.  ,  2715.  , 10500.  ,   546.  ,  1970.  ,
        1907.  ,  1130.  ,  2755.  ,  2432.  ,  1327.  ,  1089.  ,
        3491.  ,  2160.  ,   230.  , 10200.  ,  6325.  ,  1120.  ,
        3515.  ,  2025.  ,   390.  ,  1633.  ,  9100.  ,  4225.  ,
         690.  ,  1729.  ,   885.  ,    80.  ,  2156.  ,  2370.  ,
       14687.  ,  1525.  ,  1110.  ,  4425.  ,  1052.  ,  2990.  ,
        1720.  , 13000.  ,  9450.  ,  4870.  ,   942.  ,  2565.  ,
        6935.  ,  6120.  ,  3002.69,   280.  ,   414.  ,  2880.  ,
        6080.  ,  2453.  ,   890.  ,  1385.  ,  3610.  ,  3845.  ,
        6140.  ,   798.  ,  5260.  ,  4030.  ,  7250.  ,  8445.  ,
        6950.  ,  1584.  ,  1660.  ,  4880.  ,  7166.  ,  3280.  ,
        5287.  ,  5775.  ,   665.  ,  1225.  ,   415.  ,  4360.  ,
         225.  ,   217.  ,  1255.  ,  5432.  ,  5776.  ,  3896.  ,
        4210.  ,  1223.  ,  1030.  ,  1624.  ,  3470.  ,   847.  ,
        3180.  ,  1530.  ,  1562.  ,    50.  ,  2190.  ,  4072.  ,
        1068.  ,  1256.  ,  1556.  ,   319.  ,   830.  ,  1063.  ,
         824.  ,  2125.  ,   492.  ,  2770.  ,   617.  ,  2277.  ,
        6526.  ,  7083.  ,  1268.  ,  1060.  ,  3095.  ,   840.  ,
        3908.  ,  1513.  ,  1671.  ,  5667.  ,  7320.  ,  4740.  ,
        3480.  ,  4802.  ,  1955.  ,  2610.  ,  4530.  ,  2170.  ,
        1368.  ,  3670.  ,  4480.  ,  1251.  ,   882.  ,  5411.  ,
         835.  ,   460.  ,  1912.  ,  5036.  ,  4137.  ,  3720.  ,
         459.  ,  3855.  ,   440.  ,  6860.  ,  5373.  ,  3120.  ,
        2034.  ,   224.  ,   433.  ,   934.  ,   542.  ,  1730.  ,
        6792.  ,  9400.  ,  2612.  ,  1711.  ,  1805.  ,  4926.  ,
        2128.  ,  1465.  ,  9310.  ,  1765.  ,   523.  ,  1122.  ,
        6272.  ,  1945.  ,   468.  ,  5440.  ,  2404.  ,  2244.  ,
        2055.  ,   327.  ,   745.  ,  5275.  ,  3683.  ,   628.  ,
        3833.  ,  2729.  ,  2616.  ,   677.  ,  1810.  ,   988.  ,
        2220.  ,  2480.  , 12100.  ,  1782.  ,  5340.  ,   310.  ,
        9600.  ,   995.  ,  1275.  ,  5836.  ,  5860.  ,  2665.  ,
         784.  ,  1195.  ,  3520.  ,   243.76,  1448.  ,  4044.69,
         908.  ,  3830.  ,   956.  ,   220.  ,  2335.  ,  1472.  ,
        1075.  ,   476.  ,  8150.  ,  2978.  ,  1468.  ,   685.  ,
         360.  ,  4330.  ,  2675.  ,  3044.  ,  2625.  ,  1155.  ,
        1570.  ,  7425.  ,  1360.  ,  4456.  ,   683.  ,   324.  ,
        3740.  ,  5470.  ,  4970.  ,  1190.  ,  1666.  ,  1641.  ,
        9285.  ,  2206.  ,  3215.  ,   826.  ,  6790.  ,   743.  ,
        4224.  ,  4830.  ,  1820.  ,   710.  ,  7175.  , 12600.  ,
        2285.  ,  1274.  ,  1596.  ,  3145.  ,   545.  ,  1320.  ,
         589.  ,   533.  ,  2780.  ,  5115.  ,  1663.  ,   563.  ,
        5162.  ,  5190.  ,  1408.  ,  5950.  ,  7375.  ,  1528.  ,
        1325.  ,   491.  ,  2111.  ,  5454.  ,  1175.  ,  1326.  ,
         272.  ,   467.  ,  2060.  ,  1717.  ,  2975.  ,  1156.  ,
        3790.  ,   958.  ,   876.  ,   407.  ,   271.  ,  3975.  ,
         163.  ,  2165.  ,  1930.  ])

In [13]:
df['Ваш вік'].unique()

array(['29', '36', '34', '23', '33', '31', '30', '24', '27', '17', '25',
       '20', '26', '22', '19', '21', '18', '32', '35', '28', '37', '43',
       '44', '39', '50', '40', '38', '41', '45', '42', '49', '46', '47',
       '48', '55', '63', '58', '53', '54', '51', '56', '60', '16', '57',
       '29,5', '52', '14'], dtype=object)

In [14]:
df['Ваш вік'] = df['Ваш вік'].astype('str')
df['Ваш вік'] = df['Ваш вік'].str.replace(',','.')
df['Ваш вік'] = df['Ваш вік'].str.strip()
df['Ваш вік'] = df['Ваш вік'].astype('float')
df['Ваш вік'].unique()

array([29. , 36. , 34. , 23. , 33. , 31. , 30. , 24. , 27. , 17. , 25. ,
       20. , 26. , 22. , 19. , 21. , 18. , 32. , 35. , 28. , 37. , 43. ,
       44. , 39. , 50. , 40. , 38. , 41. , 45. , 42. , 49. , 46. , 47. ,
       48. , 55. , 63. , 58. , 53. , 54. , 51. , 56. , 60. , 16. , 57. ,
       29.5, 52. , 14. ])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13315 entries, 0 to 13314
Data columns (total 28 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Timestamp                                                                   13315 non-null  object
 1   Ви працюєте зараз в ІТ?                                                     13315 non-null  object
 2   Де ви зараз живете?                                                         13315 non-null  object
 3   В якій області ви зараз живете?                                             11538 non-null  object
 4   Зарплата у $$$ за місяць, лише ставка після сплати податків                 13315 non-null  float64
 5   Ваша стать                                                                  13315 non-null  object
 6   Ваш вік                                                                     13315 non-null  float64
 7   Яка у вас освіта?                                                           13315 non-null  object
 8   Чи є у вас науковий ступінь?                                                13204 non-null  object
 9   Знання англійської мови                                                     13315 non-null  object
 10  Оберіть вашу посаду                                                         13315 non-null  object
 11  Ваш тайтл                                                                   13315 non-null  object
 12  Ваша спеціалізація                                                          159 non-null    object
 13  Вкажіть вашу спеціалізацію                                                  2364 non-null   object
 14  Оберіть вашу спеціалізацію                                                  486 non-null    object
 15  Ваша посада                                                                 305 non-null    object
 16  Оберіть вашу посаду2                                                        560 non-null    object
 17  Ваша посада3                                                                821 non-null    object
 18  Ваша посада4                                                                485 non-null    object
 19  Ваша посада5                                                                288 non-null    object
 20  Ваша посада6                                                                353 non-null    object
 21  Ваша посада7                                                                116 non-null    object
 22  Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?  4874 non-null   object
 23  Основна мова програмування                                                  9060 non-null   object
 24  Вкажіть вашу основну спеціалізацію                                          9059 non-null   object
 25  В якій сфері працюєте?                                                      13315 non-null  object
 26  Тип компанії                                                                13315 non-null  object
 27  Загальний стаж роботи за спеціальністю                                      13315 non-null  object
dtypes: float64(2), object(26)
memory usage: 2.8+ MB

7. Це завдання з зірочкою! Нам треба транфсформувати колонку Timestamp у тип даних `datetime64[ns]`. Це не так просто як здається на першйий погляд :) Але це реальна ситуація, яка може трапитись при зборі даних в роботі аналітиком.
Я запропоную один зі способів виконати завдання, але ви можете написати по-своєму. Головне - отримати колонку - потрібного типу.
Пропоную наступний алгоритм дій:
    1. Подивитись, які дані містяться в цій колонці. Виведіть перші і останні 5 записів. Чи однаковий формат цих даних? (спойлер: ні, бо інакше все було б просто :))
    2. Нам треба враховуючи різний формат даних перетворити рядок у колонці `Timestamp` на тип `datetime64[ns]`. Як це зробити? Для перетворення рядка на `datetime64` пропоную скористатись `datetime.datetime.strptime`.
    Для цього треба імпортувати бібліотеку `datetime`. Я пропоную написати функцію для обробки кожного окремого рядка, яка враховує довжину рядка і на основі цього застосовує різний формат даних дати.
    Як прописувати формат даних можна переглянути [тут](https://www.w3schools.com/python/python_datetime.asp).
    3. Коли функція для обробки кожного окремого рядка готова, застосуйте її для всіх даних з допомогою методу `apply`.

In [16]:
df.head()

,Timestamp,Ви працюєте зараз в ІТ?,Де ви зараз живете?,В якій області ви зараз живете?,"Зарплата у $$$ за місяць, лише ставка після сплати податків",Ваша стать,Ваш вік,Яка у вас освіта?,Чи є у вас науковий ступінь?,Знання англійської мови,...,Ваша посада4,Ваша посада5,Ваша посада6,Ваша посада7,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,Вкажіть вашу основну спеціалізацію,В якій сфері працюєте?,Тип компанії,Загальний стаж роботи за спеціальністю
0,11.30.2022 10:26:37,"Так, працюю part-time",В Україні,Івано-Франківськ чи область,4000.0,Чоловік,29.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blockchain,Стартап,8 років
1,11.30.2022 10:26:39,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,0.0,Чоловік,36.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Advanced,...,NaN,NaN,NaN,NaN,NaN,Ruby,Full Stack розробка,Public services / Government,Продуктова,3 роки
2,11.30.2022 10:26:58,"Так, працюю full-time",В Україні,Київ чи область,2500.0,Чоловік,34.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Elementary,...,NaN,NaN,NaN,NaN,NaN,C# / .NET,Full Stack розробка,"Adtech / Advertising, Security, Telecom",Продуктова,4 роки
3,11.30.2022 10:27:31,"Так, працюю full-time",В Україні,Львів чи область,500.0,Жінка,23.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Pre-Intermediate,...,NaN,NaN,NaN,NaN,"Ні, не використовую",NaN,NaN,Telecom,Продуктова,Пів року
4,11.30.2022 10:27:34,"Ні, тимчасово не працюю",В Україні,Житомир чи область,2800.0,Жінка,33.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,"Ні, не використовую",NaN,NaN,Automotive,Продуктова,6 років

In [17]:
df.tail()

,Timestamp,Ви працюєте зараз в ІТ?,Де ви зараз живете?,В якій області ви зараз живете?,"Зарплата у $$$ за місяць, лише ставка після сплати податків",Ваша стать,Ваш вік,Яка у вас освіта?,Чи є у вас науковий ступінь?,Знання англійської мови,...,Ваша посада4,Ваша посада5,Ваша посада6,Ваша посада7,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,Вкажіть вашу основну спеціалізацію,В якій сфері працюєте?,Тип компанії,Загальний стаж роботи за спеціальністю
13310,01.09.2023 11:01,"Так, працюю full-time",В Україні,Харків чи область,4000.0,Чоловік,25.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,"Так, використовую",TypeScript,QA,Medtech / Healthcare,Продуктова,6 років
13311,01.09.2023 11:14,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,3500.0,Чоловік,28.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,JavaScript,Front-end розробка,Blockchain,Аутсорсингова,5 років
13312,01.09.2023 11:19,"Так, працюю full-time",В Україні,Дніпро чи область,1930.0,Чоловік,25.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Blockchain, Fintech / Banking, Mobile",Аутсорсингова,3 роки
13313,01.09.2023 11:28,"Так, працюю full-time",В Україні,Одеса чи область,4500.0,Чоловік,31.0,Середня,Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,NaN,JavaScript,Full Stack розробка,Mobile,Продуктова,8 років
13314,01.09.2023 11:38,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,4200.0,Чоловік,32.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,NaN,PHP,Back-end розробка,"High Load Systems, Media",Аутстафінгова,11 років

In [18]:
df['Timestamp'].str.len().unique()

array([19, 16, 18])

In [19]:
import datetime

def convert_time(date_string):
  try:
    if len(date_string) == 19 or len(date_string) == 18:
      return datetime.datetime.strptime(date_string, "%m.%d.%Y %H:%M:%S")
    elif len(date_string) == 16:
      return datetime.datetime.strptime(date_string, "%m.%d.%Y %H:%M")
    else:
      return date_string
  except ValueError as e:
      print(f"Помилка обробки: {date_string}. Помилка: {e}")
      return date_string

df['Timestamp'] = df['Timestamp'].apply(convert_time)

In [20]:
df.head(5)

,Timestamp,Ви працюєте зараз в ІТ?,Де ви зараз живете?,В якій області ви зараз живете?,"Зарплата у $$$ за місяць, лише ставка після сплати податків",Ваша стать,Ваш вік,Яка у вас освіта?,Чи є у вас науковий ступінь?,Знання англійської мови,...,Ваша посада4,Ваша посада5,Ваша посада6,Ваша посада7,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,Вкажіть вашу основну спеціалізацію,В якій сфері працюєте?,Тип компанії,Загальний стаж роботи за спеціальністю
0,2022-11-30 10:26:37,"Так, працюю part-time",В Україні,Івано-Франківськ чи область,4000.0,Чоловік,29.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blockchain,Стартап,8 років
1,2022-11-30 10:26:39,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,0.0,Чоловік,36.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Advanced,...,NaN,NaN,NaN,NaN,NaN,Ruby,Full Stack розробка,Public services / Government,Продуктова,3 роки
2,2022-11-30 10:26:58,"Так, працюю full-time",В Україні,Київ чи область,2500.0,Чоловік,34.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Elementary,...,NaN,NaN,NaN,NaN,NaN,C# / .NET,Full Stack розробка,"Adtech / Advertising, Security, Telecom",Продуктова,4 роки
3,2022-11-30 10:27:31,"Так, працюю full-time",В Україні,Львів чи область,500.0,Жінка,23.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Pre-Intermediate,...,NaN,NaN,NaN,NaN,"Ні, не використовую",NaN,NaN,Telecom,Продуктова,Пів року
4,2022-11-30 10:27:34,"Ні, тимчасово не працюю",В Україні,Житомир чи область,2800.0,Жінка,33.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Upper-Intermediate,...,NaN,NaN,NaN,NaN,"Ні, не використовую",NaN,NaN,Automotive,Продуктова,6 років

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13315 entries, 0 to 13314
Data columns (total 28 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Timestamp                                                                   13315 non-null  datetime64[ns]
 1   Ви працюєте зараз в ІТ?                                                     13315 non-null  object
 2   Де ви зараз живете?                                                         13315 non-null  object
 3   В якій області ви зараз живете?                                             11538 non-null  object
 4   Зарплата у $$$ за місяць, лише ставка після сплати податків                 13315 non-null  float64
 5   Ваша стать                                                                  13315 non-null  object
 6   Ваш вік                                                                     13315 non-null  float64
 7   Яка у вас освіта?                                                           13315 non-null  object
 8   Чи є у вас науковий ступінь?                                                13204 non-null  object
 9   Знання англійської мови                                                     13315 non-null  object
 10  Оберіть вашу посаду                                                         13315 non-null  object
 11  Ваш тайтл                                                                   13315 non-null  object
 12  Ваша спеціалізація                                                          159 non-null    object
 13  Вкажіть вашу спеціалізацію                                                  2364 non-null   object
 14  Оберіть вашу спеціалізацію                                                  486 non-null    object
 15  Ваша посада                                                                 305 non-null    object
 16  Оберіть вашу посаду2                                                        560 non-null    object
 17  Ваша посада3                                                                821 non-null    object
 18  Ваша посада4                                                                485 non-null    object
 19  Ваша посада5                                                                288 non-null    object
 20  Ваша посада6                                                                353 non-null    object
 21  Ваша посада7                                                                116 non-null    object
 22  Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?  4874 non-null   object
 23  Основна мова програмування                                                  9060 non-null   object
 24  Вкажіть вашу основну спеціалізацію                                          9059 non-null   object
 25  В якій сфері працюєте?                                                      13315 non-null  object
 26  Тип компанії                                                                13315 non-null  object
 27  Загальний стаж роботи за спеціальністю                                      13315 non-null  object
dtypes: datetime64[ns](1), float64(2), object(25)
memory usage: 2.8+ MB

8. Для колонок типу даних object (які такими лишились після всіх наших трансформацій) виведіть кількість унікальних значень.

In [22]:
df.select_dtypes('object').nunique()

Ви працюєте зараз в ІТ?                                                          5
Де ви зараз живете?                                                              2
В якій області ви зараз живете?                                                 23
Ваша стать                                                                       2
Яка у вас освіта?                                                                5
Чи є у вас науковий ступінь?                                                     3
Знання англійської мови                                                          5
Оберіть вашу посаду                                                             22
Ваш тайтл                                                                       10
Ваша спеціалізація                                                               8
Вкажіть вашу спеціалізацію                                                       4
Оберіть вашу спеціалізацію                                                      21
Ваша посада                                                                     15
Оберіть вашу посаду2                                                             7
Ваша посада3                                                                     7
Ваша посада4                                                                     5
Ваша посада5                                                                     6
Ваша посада6                                                                     2
Ваша посада7                                                                     4
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?       2
Основна мова програмування                                                      33
Вкажіть вашу основну спеціалізацію                                              12
В якій сфері працюєте?                                                        1768
Тип компанії                                                                     6
Загальний стаж роботи за спеціальністю                                          19
dtype: int64

9. Для колонок типу даних object виведіть топ 10 найбільш частих значень з кількістю рядків, в яких це значення зустрічається. Зробіть це для кожної колонки окремо. Наприклад, в циклі.  
Що цікавого бачите? Які висновки можна зробити? Що особисто Вас вразило?

In [23]:
df['Тип компанії'].value_counts().sort_values(ascending=False).head(2)

Тип компанії
Аутсорсингова    5593
Продуктова       4940
Name: count, dtype: int64

In [24]:
top_10_in_object_columns = dict()

for i in df.select_dtypes('object').columns:
  value_counts = df[i].value_counts().sort_values(ascending=False).head(10)
  top_10_in_object_columns[i] = {value : count for value, count in value_counts.items()}

  print(f'Назва колонки: {i}')
  for top_value, top_count in top_10_in_object_columns[i].items():
    print(f'Значення: {top_value} - Частота: {top_count}')

Назва колонки: Ви працюєте зараз в ІТ?
Значення: Так, працюю full-time - Частота: 12643
Значення: Ні, тимчасово не працюю - Частота: 380
Значення: Так, працюю part-time - Частота: 152
Значення: Так, я фрилансер - Частота: 115
Значення: Інше - Частота: 25
Назва колонки: Де ви зараз живете?
Значення: В Україні - Частота: 11587
Значення: За кордоном (переїхали через війну, але планую повернутися) - Частота: 1728
Назва колонки: В якій області ви зараз живете?
Значення: Київ чи область - Частота: 4411
Значення: Львів чи область - Частота: 2353
Значення: Дніпро чи область - Частота: 751
Значення: Івано-Франківськ чи область - Частота: 478
Значення: Вінниця чи область - Частота: 447
Значення: Одеса чи область - Частота: 443
Значення: Харків чи область - Частота: 355
Значення: Полтава чи область - Частота: 252
Значення: Черкаси чи область - Частота: 232
Значення: Хмельницький чи область - Частота: 230
Назва колонки: Ваша стать
Значення: Чоловік - Частота: 10221
Значення: Жінка - Частота: 3094
Назва колонки: Яка у вас освіта?
Значення: Вища (бакалавр, спеціаліст, магістр) - Частота: 10645
Значення: Дві вищі - Частота: 1002
Значення: Ще студент вишу - Частота: 811
Значення: Середня - Частота: 447
Значення: Середня спеціальна - Частота: 410
Назва колонки: Чи є у вас науковий ступінь?
Значення: Немає - Частота: 12980
Значення: Кандидат наук / PhD - Частота: 216
Значення: Доктор наук - Частота: 8
Назва колонки: Знання англійської мови
Значення: Upper-Intermediate - Частота: 5538
Значення: Intermediate - Частота: 4475
Значення: Advanced - Частота: 1622
Значення: Pre-Intermediate - Частота: 1401
Значення: Elementary - Частота: 279
Назва колонки: Оберіть вашу посаду
Значення: Software Engineer (Junior, Middle, Senior, Team/Tech Lead, Architect) - Частота: 6773
Значення: QA Engineer (Junior, Middle, Senior, Team/Tech Lead, Manager) - Частота: 2364
Значення: Project/Product/Program Manager, Product Owner, Scrum Master, Delivery Manager - Частота: 821
Значення: HR/Recruiter - Частота: 560
Значення: Designer / Artist (Graphic, UX/UI, Game, Artist, Sound etc.) - Частота: 486
Значення: Analyst (Business, Data, System) - Частота: 485
Значення: DevOps, SRE - Частота: 353
Значення: Marketing, SEO, Copywriter - Частота: 305
Значення: Data Science, Machine Learning, Big Data - Частота: 288
Значення: Game Developer / Programmer - Частота: 160
Назва колонки: Ваш тайтл
Значення: Middle - Частота: 4710
Значення: Senior - Частота: 3400
Значення: Junior - Частота: 2316
Значення: Team Lead - Частота: 883
Значення: Немає тайтлу - Частота: 571
Значення: Tech Lead - Частота: 430
Значення: Manager - Частота: 375
Значення: Head - Частота: 250
Значення: Intern/Trainee - Частота: 240
Значення: Architect - Частота: 140
Назва колонки: Ваша спеціалізація
Значення: Programmer - Частота: 89
Значення: Gameplay Programmer - Частота: 42
Значення: Engine Programmer - Частота: 8
Значення: .NET Programmer - Частота: 6
Значення: Ul Programmer - Частота: 4
Значення: Rendering/Graphics Programmer - Частота: 4
Значення: Al Programmer - Частота: 3
Значення: Інше - Частота: 3
Назва колонки: Вкажіть вашу спеціалізацію
Значення: Manual QA - Частота: 1467
Значення: Automation QA - Частота: 531
Значення: General QA - Частота: 354
Значення: Performance QA - Частота: 12
Назва колонки: Оберіть вашу спеціалізацію
Значення: UI/UX Designer - Частота: 201
Значення: Product Designer - Частота: 60
Значення: 3D Artist - Частота: 40
Значення: 2D Artist - Частота: 35
Значення: Graphic / Video Designer - Частота: 33
Значення: Game Designer - Частота: 20
Значення: Designer - Частота: 15
Значення: Animator - Частота: 14
Значення: Other - Частота: 12
Значення: Web Designer - Частота: 11
Назва колонки: Ваша посада
Значення: Other - Частота: 44
Значення: Marketing Manager - Частота: 44
Значення: SEO Specialist - Частота: 34
Значення: Digital Marketing Manager - Частота: 33
Значення: Copywriter - Частота: 27
Значення: Chief Marketing Officer (CMO) - Частота: 22
Значення: Employer Brand Manager - Частота: 20
Значення: SMM Manager - Частота: 20
Значення: PR Manager - Частота: 16
Значення: Product Marketing Manager - Частота: 11
Назва колонки: Оберіть вашу посаду2
Значення: Recruiter - Частота: 201
Значення: HR Manager - Частота: 131
Значення: Talent Acquisition Manager - Частота: 52
Значення: Talent Researcher/Sourcer - Частота: 51
Значення: HR Director - Частота: 45
Значення: HR Business Partner - Частота: 40
Значення: People partner / Happiness manager - Частота: 40
Назва колонки: Ваша посада3
Значення: Project Manager - Частота: 443
Значення: Product Manager - Частота: 135
Значення: Delivery Manager - Частота: 88
Значення: Product Owner - Частота: 67
Значення: Scrum Master - Частота: 42
Значення: Program Manager - Частота: 29
Значення: Business Manager - Частота: 17
Назва колонки: Ваша посада4
Значення: Business Analyst - Частота: 289
Значення: Data Analyst - Частота: 106
Значення: Product Analyst - Частота: 34
Значення: System Analyst - Частота: 32
Значення: BI Analyst - Частота: 24
Назва колонки: Ваша посада5
Значення: Data Engineer / Big Data Engineer - Частота: 104
Значення: Data Scientist - Частота: 93
Значення: Machine Learning Engineer - Частота: 46
Значення: Computer Vision Engineer - Частота: 21
Значення: Research Engineer - Частота: 15
Значення: BI Engineer - Частота: 9
Назва колонки: Ваша посада6
Значення: DevOps Engineer - Частота: 325
Значення: Site Reliability Engineer - Частота: 28
Назва колонки: Ваша посада7
Значення: CTO - Частота: 41
Значення: Director of Engineering - Частота: 33
Значення: CEO, (co-) founder - Частота: 28
Значення: Program Director - Частота: 14
Назва колонки: Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?
Значення: Ні, не використовую - Частота: 2754
Значення: Так, використовую - Частота: 2120
Назва колонки: Основна мова програмування
Значення: JavaScript - Частота: 1695
Значення: Java - Частота: 1241
Значення: Python - Частота: 1190
Значення: TypeScript - Частота: 1179
Значення: C# / .NET - Частота: 1179
Значення: PHP - Частота: 627
Значення: Kotlin - Частота: 286
Значення: C++ - Частота: 251
Значення: Swift - Частота: 221
Значення: SQL - Частота: 201
Назва колонки: Вкажіть вашу основну спеціалізацію
Значення: Back-end  розробка - Частота: 2847
Значення: Full Stack розробка - Частота: 1628
Значення: Front-end  розробка - Частота: 1628
Значення: QA - Частота: 1079
Значення: Mobile  розробка - Частота: 665
Значення: Робота з даними, аналіз даних - Частота: 558
Значення: DevOps - Частота: 308
Значення: Інше - Частота: 293
Значення: Embedded - Частота: 49
Значення: embedded - Частота: 2
Назва колонки: В якій сфері працюєте?
Значення: Інша - Частота: 1445
Значення: E-commerce - Частота: 1243
Значення: Fintech / Banking - Частота: 942
Значення: Medtech / Healthcare - Частота: 547
Значення: GameDev - Частота: 449
Значення: Gambling - Частота: 352
Значення: Edtech / Education - Частота: 250
Значення: Telecom - Частота: 232
Значення: Mobile - Частота: 200
Значення: Adtech / Advertising - Частота: 193
Назва колонки: Тип компанії
Значення: Аутсорсингова - Частота: 5593
Значення: Продуктова - Частота: 4940
Значення: Аутстафінгова - Частота: 1767
Значення: Стартап - Частота: 539
Значення: Інша - Частота: 355
Значення: Фріланс - Частота: 121
Назва колонки: Загальний стаж роботи за спеціальністю
Значення: 3 роки - Частота: 1608
Значення: 4 роки - Частота: 1447
Значення: 2 роки - Частота: 1427
Значення: 5 років - Частота: 1351
Значення: 1,5 року - Частота: 1056
Значення: 6 років - Частота: 982
Значення: 1 рік - Частота: 922
Значення: 7 років - Частота: 791
Значення: 10 років - Частота: 599
Значення: 15 і більше років - Частота: 586

10. Виведіть медіанну (медіана - це значення, менше якого є рівно 50% вибірки і більше якого є теж рівно 50% вибірки)
ЗП (Зарплата у $$$) для кожного рівня знання англійської. Які висновки можна зробити?

In [25]:
df.groupby('Знання англійської мови')['Зарплата у $$$ за місяць, лише ставка після сплати податків'].median().sort_values(ascending=False)

Знання англійської мови
Advanced              3500.0
Upper-Intermediate    3300.0
Intermediate          2100.0
Pre-Intermediate      1400.0
Elementary            1155.0
Name: Зарплата у $$$ за місяць, лише ставка після сплати податків, dtype: float64


**Висновок:**

Чим вищий рівень знання англійської мови, тим вище ЗП.

**11**. Є така штука як сортування значень категоріальної змінної. Нам це зараз стане в нагоді, адже рівні англійської можна посортувати.
Давайте відсотруємо рівні англ. і тайтли. Просто запустіть код нижче і проаналізуйте, що він робить.

In [26]:
df['Знання англійської мови'] = pd.Categorical(df['Знання англійської мови'],
                      categories=['Elementary','Pre-Intermediate','Intermediate','Upper-Intermediate','Advanced'],
                      ordered=True)

df['Ваш тайтл'] = pd.Categorical(df['Ваш тайтл'],
                      categories=['Intern/Trainee', 'Junior', 'Немає тайтлу', 'Middle', 'Senior', 'Tech Lead', 'Team Lead', 'Architect', 'Head', 'Manager'],
                      ordered=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13315 entries, 0 to 13314
Data columns (total 28 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Timestamp                                                                   13315 non-null  datetime64[ns]
 1   Ви працюєте зараз в ІТ?                                                     13315 non-null  object
 2   Де ви зараз живете?                                                         13315 non-null  object
 3   В якій області ви зараз живете?                                             11538 non-null  object
 4   Зарплата у $$$ за місяць, лише ставка після сплати податків                 13315 non-null  float64
 5   Ваша стать                                                                  13315 non-null  object
 6   Ваш вік                                                                     13315 non-null  float64
 7   Яка у вас освіта?                                                           13315 non-null  object
 8   Чи є у вас науковий ступінь?                                                13204 non-null  object
 9   Знання англійської мови                                                     13315 non-null  category
 10  Оберіть вашу посаду                                                         13315 non-null  object
 11  Ваш тайтл                                                                   13315 non-null  category
 12  Ваша спеціалізація                                                          159 non-null    object
 13  Вкажіть вашу спеціалізацію                                                  2364 non-null   object
 14  Оберіть вашу спеціалізацію                                                  486 non-null    object
 15  Ваша посада                                                                 305 non-null    object
 16  Оберіть вашу посаду2                                                        560 non-null    object
 17  Ваша посада3                                                                821 non-null    object
 18  Ваша посада4                                                                485 non-null    object
 19  Ваша посада5                                                                288 non-null    object
 20  Ваша посада6                                                                353 non-null    object
 21  Ваша посада7                                                                116 non-null    object
 22  Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?  4874 non-null   object
 23  Основна мова програмування                                                  9060 non-null   object
 24  Вкажіть вашу основну спеціалізацію                                          9059 non-null   object
 25  В якій сфері працюєте?                                                      13315 non-null  object
 26  Тип компанії                                                                13315 non-null  object
 27  Загальний стаж роботи за спеціальністю                                      13315 non-null  object
dtypes: category(2), datetime64[ns](1), float64(2), object(23)
memory usage: 2.7+ MB

In [28]:
df.head(3)

,Timestamp,Ви працюєте зараз в ІТ?,Де ви зараз живете?,В якій області ви зараз живете?,"Зарплата у $$$ за місяць, лише ставка після сплати податків",Ваша стать,Ваш вік,Яка у вас освіта?,Чи є у вас науковий ступінь?,Знання англійської мови,...,Ваша посада4,Ваша посада5,Ваша посада6,Ваша посада7,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,Вкажіть вашу основну спеціалізацію,В якій сфері працюєте?,Тип компанії,Загальний стаж роботи за спеціальністю
0,2022-11-30 10:26:37,"Так, працюю part-time",В Україні,Івано-Франківськ чи область,4000.0,Чоловік,29.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Intermediate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blockchain,Стартап,8 років
1,2022-11-30 10:26:39,"Так, працюю full-time","За кордоном (переїхали через війну, але планую...",NaN,0.0,Чоловік,36.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Advanced,...,NaN,NaN,NaN,NaN,NaN,Ruby,Full Stack розробка,Public services / Government,Продуктова,3 роки
2,2022-11-30 10:26:58,"Так, працюю full-time",В Україні,Київ чи область,2500.0,Чоловік,34.0,"Вища (бакалавр, спеціаліст, магістр)",Немає,Elementary,...,NaN,NaN,NaN,NaN,NaN,C# / .NET,Full Stack розробка,"Adtech / Advertising, Security, Telecom",Продуктова,4 роки

In [29]:
df.memory_usage()

Index                                                                            128
Timestamp                                                                     106520
Ви працюєте зараз в ІТ?                                                       106520
Де ви зараз живете?                                                           106520
В якій області ви зараз живете?                                               106520
Зарплата у $$$ за місяць, лише ставка після сплати податків                   106520
Ваша стать                                                                    106520
Ваш вік                                                                       106520
Яка у вас освіта?                                                             106520
Чи є у вас науковий ступінь?                                                  106520
Знання англійської мови                                                        13527
Оберіть вашу посаду                                                           106520
Ваш тайтл                                                                      13695
Ваша спеціалізація                                                            106520
Вкажіть вашу спеціалізацію                                                    106520
Оберіть вашу спеціалізацію                                                    106520
Ваша посада                                                                   106520
Оберіть вашу посаду2                                                          106520
Ваша посада3                                                                  106520
Ваша посада4                                                                  106520
Ваша посада5                                                                  106520
Ваша посада6                                                                  106520
Ваша посада7                                                                  106520
Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?    106520
Основна мова програмування                                                    106520
Вкажіть вашу основну спеціалізацію                                            106520
В якій сфері працюєте?                                                        106520
Тип компанії                                                                  106520
Загальний стаж роботи за спеціальністю                                        106520
dtype: int64

Після перетворення даних колонок в категоріальний тип зменшився об'єм пам'яті, який займають ці дані. Також з'явилася змога логічного сортування та порівняння значень за цими колонками.

12. Зробіть зводну таблицю, де стовпці - це 'Ваш тайтл', рядки - 'Знання англійської мови', а значення - медіанна ЗП. Які висновки можна зробити?
Тут ще для зручності можна зробити градієнтне забарвлення і відформатувати значення для легшого перегляду.

In [30]:
piv_table = pd.pivot_table(df, index=['Знання англійської мови'], columns=['Ваш тайтл'], values=['Зарплата у $$$ за місяць, лише ставка після сплати податків'], aggfunc=['median'], observed=True)
piv_table

                                                                             median  \
                        Зарплата у $$$ за місяць, лише ставка після сплати податків
Ваш тайтл                                                            Intern/Trainee
Знання англійської мови
Elementary                                                           500.0
Pre-Intermediate                                                     400.0
Intermediate                                                         400.0
Upper-Intermediate                                                   485.0
Advanced                                                             500.0

                                                                        \

Ваш тайтл                Junior Немає тайтлу  Middle  Senior Tech Lead
Знання англійської мови
Elementary                600.0        550.0  1500.0  2500.0    5000.0
Pre-Intermediate          800.0        934.0  1800.0  3500.0    4000.0
Intermediate              900.0       1300.0  2200.0  4100.0    5000.0
Upper-Intermediate       1000.0       1600.0  2500.0  4750.0    5650.0
Advanced                 1000.0       2075.0  2470.0  4750.0    6000.0



Ваш тайтл               Team Lead Architect    Head Manager
Знання англійської мови
Elementary                 2100.0       NaN  1500.0  1120.0
Pre-Intermediate           2850.0    2900.0  2400.0  1225.0
Intermediate               3800.0    5450.0  3500.0  2100.0
Upper-Intermediate         4627.5    6350.0  4000.0  3550.0
Advanced                   5000.0    7000.0  5000.0  4000.0

In [31]:
# https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.background_gradient.html
piv_table.style.background_gradient(axis=None, cmap='coolwarm').format('{:.0f}')

Чим вищий рівень знання англійської мови та/або посада, тим вище ЗП.

13. Виведіть результат методу describe() по колонцы розміру ЗП для топ 5 за частотою зустрічання в даних областей (В якій області ви зараз живете?). Зробіть висновки, де вигідніше жити з точки зору ЗП і чи суттєва різниця на Ваш погляд для прийняття рішення про переїзд?

In [32]:
# переглянемо частоту по всім областям (для контролю топ-5)
df['В якій області ви зараз живете?'].value_counts()

В якій області ви зараз живете?
Київ чи область                    4411
Львів чи область                   2353
Дніпро чи область                   751
Івано-Франківськ чи область         478
Вінниця чи область                  447
Одеса чи область                    443
Харків чи область                   355
Полтава чи область                  252
Черкаси чи область                  232
Хмельницький чи область             230
Тернопіль чи область                223
Чернівці чи область                 211
Ужгород чи Закарпатська область     186
Рівне чи область                    180
Житомир чи область                  174
Луцьк чи Волинська область          153
Кропивницький чи область            121
Запоріжжя чи область                102
Суми чи область                     101
Чернігів чи область                  81
Миколаїв чи область                  45
Донецька чи Луганська область         6
Херсон чи область                     3
Name: count, dtype: int64

In [33]:
#відбираємо топ-5 областей
top_5 = df['В якій області ви зараз живете?'].value_counts().head(5).index

#вібираємо частину дата-фрейму, який відноситься до обраних областей
filter = df[df['В якій області ви зараз живете?'].isin(top_5)]

#по відібраним даним будуємо групування та будуємо таблицю з описом (сортування зробимо по частоті області в порядку за спаданням значень).
# Також застосуэмо градієнт з попереднтого завдання, але з параметром axis=0
filter.groupby('В якій області ви зараз живете?')['Зарплата у $$$ за місяць, лише ставка після сплати податків'].describe().sort_values(by='count', ascending=False).style.background_gradient(axis=0, cmap='coolwarm').format('{:.0f}')

Результати обробки дата-фрейму показують, що нема великої доцільності переїзду наприклад, з Вінницької області до Києвської - рівень ЗП відрізняється незначною мірою (якщо не брати до уваги  максимальні значення даних). Відібрані дані також показують значну перевагу в кількості (фактично конкуренцію) опитаних спеціалістів в Києвській обалсті   в порівнянні з іншими облястями. Що також впливає на рішення переїзду до цієї області. Було б цікаво подивитися на кількість релевантних оголошень роботи по областях. Вважаю, що було б доцільним орієнтуватися ще на ці дані.

14. Як зростає зарплата з роками? Для цього нам треба відформатувати колонку "Загальний стаж роботи за спеціальністю" аналогічно до того, як ми це робили для колонки 'Знання англійської мови' і потім вивести медіанні значення для кількості років стажу.

In [34]:
df['Загальний стаж роботи за спеціальністю'].unique()

array(['8 років', '3 роки', '4 роки', 'Пів року', '6 років', '1,5 року',
       '1 рік', '2 роки', '5 років', '10 років', 'Менше як 3 місяці',
       '11 років', '7 років', '15 і більше років', '3 місяці', '12 років',
       '9 років', '14 років', '13 років'], dtype=object)

In [35]:
df['Загальний стаж роботи за спеціальністю'] = pd.Categorical(df['Загальний стаж роботи за спеціальністю'],
                      categories=['Менше як 3 місяці', '3 місяці', 'Пів року',  '12 років', '1,5 року',
       '1 рік', '2 роки', '3 роки', '4 роки', '5 років', '6 років','7 років', '8 років', '9 років', '10 років',
       '11 років', '13 років', '14 років', '15 і більше років'],
                      ordered=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13315 entries, 0 to 13314
Data columns (total 28 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Timestamp                                                                   13315 non-null  datetime64[ns]
 1   Ви працюєте зараз в ІТ?                                                     13315 non-null  object
 2   Де ви зараз живете?                                                         13315 non-null  object
 3   В якій області ви зараз живете?                                             11538 non-null  object
 4   Зарплата у $$$ за місяць, лише ставка після сплати податків                 13315 non-null  float64
 5   Ваша стать                                                                  13315 non-null  object
 6   Ваш вік                                                                     13315 non-null  float64
 7   Яка у вас освіта?                                                           13315 non-null  object
 8   Чи є у вас науковий ступінь?                                                13204 non-null  object
 9   Знання англійської мови                                                     13315 non-null  category
 10  Оберіть вашу посаду                                                         13315 non-null  object
 11  Ваш тайтл                                                                   13315 non-null  category
 12  Ваша спеціалізація                                                          159 non-null    object
 13  Вкажіть вашу спеціалізацію                                                  2364 non-null   object
 14  Оберіть вашу спеціалізацію                                                  486 non-null    object
 15  Ваша посада                                                                 305 non-null    object
 16  Оберіть вашу посаду2                                                        560 non-null    object
 17  Ваша посада3                                                                821 non-null    object
 18  Ваша посада4                                                                485 non-null    object
 19  Ваша посада5                                                                288 non-null    object
 20  Ваша посада6                                                                353 non-null    object
 21  Ваша посада7                                                                116 non-null    object
 22  Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?  4874 non-null   object
 23  Основна мова програмування                                                  9060 non-null   object
 24  Вкажіть вашу основну спеціалізацію                                          9059 non-null   object
 25  В якій сфері працюєте?                                                      13315 non-null  object
 26  Тип компанії                                                                13315 non-null  object
 27  Загальний стаж роботи за спеціальністю                                      13315 non-null  category
dtypes: category(3), datetime64[ns](1), float64(2), object(22)
memory usage: 2.6+ MB

In [37]:
professional_experience = pd.pivot_table(df, index=['Загальний стаж роботи за спеціальністю'], columns=['Ваш тайтл'], values=['Зарплата у $$$ за місяць, лише ставка після сплати податків'], aggfunc=['median'], observed=True)
professional_experience.style.text_gradient(axis=None, cmap='coolwarm').format('{:.0f}')

Далі тут можна зробити багато аналогічних агрегацій, проаналізувати, в який час люди заповнювали форму, хто більше отримує, Business Analyst, чи Data Analyst. Я вас заохочувати не стримувати свій інтерес і покапати ці дані далі :)