<a href="https://colab.research.google.com/github/MrCherveN/DataAnalist-7-0_HomeTasks/blob/main/hw_3_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
import pandas as pd

In [28]:
df = pd.read_csv('/content/drive/MyDrive/Python/Аналітик 7-0/Лекции/Модуль 3/data/supermarket_sales.csv')

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [40]:
#варіант 1
df.groupby('Branch')['gross income'].sum().sort_values(ascending= False).head(1)

Branch
C    5265.1765
Name: gross income, dtype: float64

In [41]:
#варіант 2
branch_gross_income = df.groupby('Branch')['gross income'].sum()
print(f"Найприбутковішим є філіал '{branch_gross_income.idxmax()}' з сумарним прибутком {branch_gross_income.max()}." )

Найприбутковішим є філіал 'C' з сумарним прибутком 5265.1765.

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [42]:
#варіант 1
df.groupby(['City','Branch'])['gross income'].sum().sort_values(ascending= False).head(1)

City       Branch
Naypyitaw  C         5265.1765
Name: gross income, dtype: float64

In [43]:
branch_city_gross_income = df.groupby(['City','Branch'])['gross income'].sum()
branch_city_gross_income

City       Branch
Mandalay   B         5057.0320
Naypyitaw  C         5265.1765
Yangon     A         5057.1605
Name: gross income, dtype: float64

In [44]:
#варіант 2
branch_city_gross_income = df.groupby(['City','Branch'])['gross income'].sum()

print(f"Філіал з найвищим прибутком знаходиться в місті '{branch_city_gross_income.idxmax()[0]}' з сумарним прибутком {branch_city_gross_income.max()}." )

Філіал з найвищим прибутком знаходиться в місті 'Naypyitaw' з сумарним прибутком 5265.1765.

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [45]:
invoices_by_category  = df.pivot_table(index='Branch', columns='Product line', values='Invoice ID',  aggfunc='count')

In [46]:
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [47]:
print(f"Найбільше інвойсів із покупкою товарів категорії 'Electronic accessories' здійснено в філіалі магазину:'{invoices_by_category['Electronic accessories'].idxmax()}'.")
print(f"Загальна калькість цих інвойсів становить {invoices_by_category['Electronic accessories'].max()} штук.")

Найбільше інвойсів із покупкою товарів категорії 'Electronic accessories' здійснено в філіалі магазину:'A'.
Загальна калькість цих інвойсів становить 60 штук.

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

**Крок 1**
1. Який розподіл по "Product line" та  "Gender" покупців по кількості покупок та за показником валового доходу з їх продажів? Чи є залежність між типом товару та гендером? Яка трійка лідерів груп товарів по кожному з "Gender" за показником валового доходу з їх продажів.

2. Який розподіл по "Product line" та "Customer type" покупців по кількості покупок та за показником валового доходу в розрізі Branch? Чи є залежність між типом товара та типом клієнта?

3. Який розподіл середнього значення "Rating" по "Gender" та "Customer type" в різних містах? Чи є якась залежність в цьому?

In [50]:
#Крок 2.

#Питаня по п.1 з Кроку 1

#Який розподіл по "Product line" та "Gender" покупців по кількості покупок
product_line_gender = pd.pivot_table(df, index=['Product line'], columns=['Gender'], values=['Invoice ID'], aggfunc= 'count')
product_line_gender.loc['Total count'] = product_line_gender.sum(numeric_only=True).values
product_line_gender = product_line_gender.rename(columns= {'Invoice ID' : 'Count'})
product_line_gender

                        Count
Gender                 Female Male
Product line
Electronic accessories     84   86
Fashion accessories        96   82
Food and beverages         90   84
Health and beauty          64   88
Home and lifestyle         79   81
Sports and travel          88   78
Total count               501  499

In [51]:
#Який розподіл по "Product line" та "Gender" покупців за показником валового доходу з їх продажів
product_line_gender_income = pd.pivot_table(df, index=['Product line'], columns=['Gender'], values=['gross income'], aggfunc=['sum']).round(2)
product_line_gender_income.columns = product_line_gender_income.columns.droplevel([0,1])

product_line_gender_income

Gender                   Female     Male
Product line
Electronic accessories  1290.57  1296.93
Fashion accessories     1449.40  1136.60
Food and beverages      1579.57  1094.00
Health and beauty        883.86  1458.70
Home and lifestyle      1430.33  1134.53
Sports and travel       1360.70  1264.20

In [52]:
product_line_male = product_line_gender_income['Male'].sort_values(ascending=False).head(3)
product_line_male

Product line
Health and beauty         1458.70
Electronic accessories    1296.93
Sports and travel         1264.20
Name: Male, dtype: float64

In [53]:
product_line_female = product_line_gender_income['Female'].sort_values(ascending=False).head(3)
product_line_female

Product line
Food and beverages     1579.57
Fashion accessories    1449.40
Home and lifestyle     1430.33
Name: Female, dtype: float64

In [54]:
# Питаня по п.2 з Кроку 1

#Який розподіл по "Product line" та "Customer type" покупців по кількості покупок та за показником валового доходу в розрізі Branch
product_line_customer_type = pd.pivot_table(df, index=['Product line'], columns=[ 'Branch','Customer type'], values=['Invoice ID', 'gross income'], aggfunc={'Invoice ID' : 'count', 'gross income' : 'sum'}).round(2).astype(int)
product_line_customer_type.loc['Total'] = product_line_customer_type.sum(numeric_only=True).values
product_line_customer_type = product_line_customer_type.rename(columns={'Invoice ID': 'Number of Purchases', 'gross income': 'Total Income'})

product_line_customer_type

                       Number of Purchases                                     \
Branch                                   A             B             C
Customer type                       Member Normal Member Normal Member Normal
Product line
Electronic accessories                  31     29     27     28     20     35
Fashion accessories                     22     29     32     30     32     33
Food and beverages                      29     29     29     21     36     30
Health and beauty                       22     25     26     27     25     27
Home and lifestyle                      34     31     21     29     28     17
Sports and travel                       29     30     30     32     28     17
Total                                  167    173    165    167    169    159

                       Total Income
Branch                            A             B             C
Customer type                Member Normal Member Normal Member Normal
Product line
Electronic accessories          435    436    353    458    377    525
Fashion accessories             330    447    349    432    573    453
Food and beverages              422    394    448    275    621    509
Health and beauty               306    293    539    412    384    407
Home and lifestyle              597    469    369    465    364    297
Sports and travel               460    461    496    455    387    363
Total                          2550   2500   2554   2497   2706   2554

In [55]:
# Питаня по п.3 з Кроку 1

#Який розподіл середнього значення "Rating" по "Gender" та "Customer type" в різних містах?
reiting_customer_type = pd.pivot_table(df, index= ['City'], columns= ['Customer type', 'Gender'], values=['Rating'], aggfunc= "mean", fill_value=0)
reiting_customer_type.loc['Total'] = reiting_customer_type.mean(numeric_only=True).values

reiting_customer_type

                 Rating
Customer type    Member              Normal
Gender           Female      Male    Female      Male
City
Mandalay       6.885882  6.647500  6.866234  6.864444
Naypyitaw      7.117708  6.957534  7.204878  6.985714
Yangon         6.786250  7.194253  6.891358  7.197826
Total          6.929947  6.933096  6.987490  7.015995

**Крок 3**

1. Аналіз розподілу продажів за гендером та типом товару допоможе бізнесу зрозуміти, які типи товарів являються фаворитами для покупців в залежності від їх статі. Тому бізнес, наприклад, може використати дану інформацію при розробці певних цілеспрямованих (тобто більш орієнтованих на певну аудиторію) програм продажів. Це може вплинути на збільшення продажів товарів в майбутньому.

2. В даному випадку відповідь на це питання допоможе бізнесу оптимізувати процес замовлення та зберігання товарів певної групи до їх продажу, що можливо вплине на зменшення витрат на зберігання великої кількості товарів з малим попитом.

3. Відповідь на це питання допоможе зрозуміти рівень задоволеності клієнтів (в залежності від їх гендеру та типу) та за потреби вплинути на ці показники, шляхом виявлення їх системності. Наприклад, можливо показники можуть бути низькими через незадовільне обслуговування клієнтів.  Звісно, для точної відповіді потрібно буде проводити більш детальний аналіз, адже середні показники не дуже інформативні 😉.